DROP TABLE user_roles IF EXISTS;
DROP TABLE restorans_dish IF EXISTS;
DROP TABLE restorans_users IF EXISTS;
DROP TABLE dish IF EXISTS;
DROP TABLE vote IF EXISTS;
DROP TABLE restorans IF EXISTS;
DROP TABLE users IF EXISTS;

DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL,
    email            VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL,
    registered       TIMESTAMP DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE dish
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    price       INTEGER NOT NULL

);

CREATE TABLE restorans
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    user_id     INTEGER      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restorans_dish
(
    dish_id         integer not null,
    restoran_id     integer not null,
    date            TIMESTAMP DEFAULT now() NOT NULL,
    CONSTRAINT FK_DISH_ID FOREIGN KEY (dish_id)
        REFERENCES dish (id),
    CONSTRAINT FK_RESTORAN_ID FOREIGN KEY (restoran_id)
        REFERENCES restorans (id)

);

CREATE TABLE vote
(
    restoran_id      integer not null,
    vote             integer not null,
    date            TIMESTAMP DEFAULT now() NOT NULL,
    FOREIGN KEY (restoran_id) REFERENCES RESTORANS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX meals_unique_user_datetime_idx ON VOTE (RESTORAN_ID, date);

CREATE TABLE restorans_users
(
    user_id         integer not null,
    restoran_id     integer not null,
    date            TIMESTAMP DEFAULT now() NOT NULL,
    CONSTRAINT FK_USER_ID FOREIGN KEY (user_id)
        REFERENCES dish (id),
    CONSTRAINT FK_RESTORAN_ID_USER FOREIGN KEY (restoran_id)
        REFERENCES restorans (id)

);